meta_product_name: "Legit Kitchen"
meta_title: "Legit Kitchen - Authentic recipes by people from around the world"
meta_description: "Legit Kitchen does exactly what it says on the tin. We are a platform for food-lovers allowing users to  Like, share and create Authentic recipes from around the world."
meta_image: "logo_coral.png" # should exist in `app/assets/images/`

